name: Android CI

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Lint
        run: ./gradlew lint

      - name: Generate Test Report
        run: |
          mkdir -p reports
          cp $(find . -path '*/test-results/test/TEST-*.xml' -print) reports/test-results.xml
          cp $(find . -path '*/reports/lint-results.xml' -print) reports/lint-results.xml

      - name: Add PR comment with test and lint results
        run: |
          TEST_RESULTS=$(cat reports/test-results.xml)
          LINT_RESULTS=$(cat reports/lint-results.xml)

          COMMENT_BODY="### Test Results\n$TEST_RESULTS\n\n### Lint Results\n$LINT_RESULTS"

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"body": "'"$COMMENT_BODY"'"}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
