name: PR Tests and Lint

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Lint
        run: |
          npm install
          npm run lint

      - name: Run tests
        run: |
          npm install
          npm test

      - name: Create PR comment with test and lint results
        run: |
          LINT_RESULT=$(npm run lint)
          TEST_RESULT=$(npm test)

          PR_COMMENT="### Lint Results\n$LINT_RESULT\n\n### Test Results\n$TEST_RESULT"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -X POST \
               -d "{\"body\": \"$PR_COMMENT\"}" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
